# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19WuFhH_x9BKft6sSjnZgnkYihsi19Jlo
"""

# earnings_analyzer.py
import os
import re
import json
import hashlib
import requests
import pandas as pd
import streamlit as st
from bs4 import BeautifulSoup
from google import genai
import yfinance as yf
from datetime import datetime, timedelta

# Configure AI
api_key = st.secrets.get("GEMINI_API_KEY") or os.environ.get("GEMINI_API_KEY")
if not api_key:
    st.error("❌ Missing Gemini API key")
    st.stop()

client = genai.Client(api_key=api_key)

# -----------------------------
# 1️⃣ SEC EDGAR Earnings Scraper
# -----------------------------
@st.cache_data(ttl=3600, show_spinner="📋 Fetching SEC filings...")
def fetch_sec_earnings(ticker, quarters=4):
    """Fetch recent 10-Q/10-K filings from SEC EDGAR"""
    filings = []
    try:
        # SEC EDGAR search URL
        search_url = f"https://www.sec.gov/cgi-bin/browse-edgar"
        params = {
            'action': 'getcompany',
            'CIK': ticker,
            'type': '10-Q',
            'dateb': '',
            'count': quarters * 2
        }

        headers = {
            'User-Agent': 'Mozilla/5.0 (compatible; Research/1.0; +http://example.com/contact)'
        }

        # Note: This is a simplified example. Real SEC scraping requires:
        # - Proper CIK lookup
        # - Rate limiting compliance
        # - XBRL parsing for structured data

        # For demo purposes, return sample data
        sample_filings = [
            {
                'date': '2024-10-30',
                'type': '10-Q',
                'period': 'Q3 2024',
                'revenue': '$50.2B',
                'net_income': '$12.8B',
                'eps': '$2.15',
                'url': f'https://www.sec.gov/sample/{ticker}-q3-2024'
            },
            {
                'date': '2024-07-31',
                'type': '10-Q',
                'period': 'Q2 2024',
                'revenue': '$48.9B',
                'net_income': '$11.5B',
                'eps': '$1.98',
                'url': f'https://www.sec.gov/sample/{ticker}-q2-2024'
            }
        ]

        return sample_filings[:quarters]

    except Exception as e:
        st.warning(f"⚠️ SEC filing fetch failed: {e}")
        return []

# -----------------------------
# 2️⃣ Earnings Call Transcript Scraper
# -----------------------------
@st.cache_data(ttl=3600, show_spinner="🎙️ Fetching earnings call transcripts...")
def fetch_earnings_transcripts(ticker, quarters=2):
    """Scrape earnings call transcripts from SeekingAlpha, MotleyFool, etc."""
    transcripts = []

    # SeekingAlpha earnings transcripts
    sources = [
        f"https://seekingalpha.com/symbol/{ticker}/earnings/transcripts",
        f"https://www.fool.com/quote/{ticker}/earnings/",
        f"https://finance.yahoo.com/quote/{ticker}/analysis"
    ]

    try:
        for source in sources:
            headers = {'User-Agent': 'Mozilla/5.0 (compatible; Research/1.0)'}

            # For demo purposes, return sample transcript data
            sample_transcript = {
                'date': '2024-10-30',
                'quarter': 'Q3 2024',
                'source': 'SeekingAlpha',
                'ceo_comments': [
                    "We delivered strong results this quarter with revenue growth of 8% year-over-year",
                    "Our new product line is gaining significant traction in the market",
                    "We remain optimistic about our growth prospects for the remainder of the year"
                ],
                'analyst_questions': [
                    "What are your expectations for margin expansion next quarter?",
                    "How is the competitive landscape affecting your market share?",
                    "Can you provide more details on your capital allocation strategy?"
                ],
                'key_metrics_discussed': [
                    "User growth rate increased 12% quarter-over-quarter",
                    "Gross margins improved to 68%, up from 65% last quarter",
                    "Free cash flow generation remains strong at $8.2B"
                ]
            }
            transcripts.append(sample_transcript)
            break  # For demo, just use one source

    except Exception as e:
        st.warning(f"⚠️ Transcript fetch failed: {e}")

    return transcripts[:quarters]

# -----------------------------
# 3️⃣ Analyst Reports & News Scraper
# -----------------------------
@st.cache_data(ttl=1800, show_spinner="📰 Collecting analyst reports...")
def fetch_analyst_sentiment(ticker, days=30):
    """Fetch recent analyst reports and news sentiment"""
    reports = []

    news_sources = [
        f"https://finance.yahoo.com/quote/{ticker}/news",
        f"https://www.marketwatch.com/investing/stock/{ticker}",
        f"https://seekingalpha.com/symbol/{ticker}/news"
    ]

    try:
        # Sample analyst data
        sample_reports = [
            {
                'date': '2024-11-01',
                'firm': 'Goldman Sachs',
                'rating': 'Buy',
                'price_target': '$180',
                'headline': 'Strong Q3 results support positive outlook',
                'key_points': [
                    'Revenue beat expectations by 3%',
                    'Margin expansion ahead of schedule',
                    'Management guidance raised for FY2024'
                ]
            },
            {
                'date': '2024-10-31',
                'firm': 'Morgan Stanley',
                'rating': 'Overweight',
                'price_target': '$175',
                'headline': 'Solid execution on strategic initiatives',
                'key_points': [
                    'Market share gains in key segments',
                    'Strong balance sheet provides flexibility',
                    'Well-positioned for economic uncertainty'
                ]
            }
        ]

        return sample_reports

    except Exception as e:
        st.warning(f"⚠️ Analyst data fetch failed: {e}")
        return []

# -----------------------------
# 4️⃣ Stock Price & Market Data
# -----------------------------
@st.cache_data(ttl=300, show_spinner="📈 Fetching market data...")
def fetch_market_data(ticker, days=90):
    """Get stock price, volume, and market reaction data"""
    try:
        stock = yf.Ticker(ticker)

        # Get recent price data
        hist = stock.history(period="3mo")

        # Get company info
        info = stock.info

        # Calculate key metrics
        current_price = hist['Close'][-1]
        price_change_30d = ((current_price - hist['Close'][-30]) / hist['Close'][-30]) * 100
        avg_volume = hist['Volume'].mean()

        market_data = {
            'current_price': current_price,
            'market_cap': info.get('marketCap', 0),
            'pe_ratio': info.get('trailingPE', 0),
            'price_change_30d': price_change_30d,
            'avg_volume': avg_volume,
            'sector': info.get('sector', 'Unknown'),
            'industry': info.get('industry', 'Unknown'),
            'price_history': hist['Close'].tolist()[-30:],  # Last 30 days
            'volume_history': hist['Volume'].tolist()[-30:]
        }

        return market_data

    except Exception as e:
        st.warning(f"⚠️ Market data fetch failed: {e}")
        return {}

# -----------------------------
# 5️⃣ AI-Powered Earnings Analysis
# -----------------------------
@st.cache_data(ttl=7200, show_spinner="🤖 Generating AI analysis...")
def analyze_earnings_with_ai(ticker, sec_filings, transcripts, analyst_reports, market_data):
    """Comprehensive AI analysis of all earnings data"""

    try:
        # Prepare data contexts
        filings_context = "\n".join([
            f"Q{i+1}: Revenue {f.get('revenue', 'N/A')}, EPS {f.get('eps', 'N/A')}, Net Income {f.get('net_income', 'N/A')}"
            for i, f in enumerate(sec_filings)
        ])

        transcript_context = "\n".join([
            f"CEO: {', '.join(t.get('ceo_comments', [])[:2])}"
            for t in transcripts
        ])

        analyst_context = "\n".join([
            f"{r.get('firm', '')}: {r.get('rating', '')} - ${r.get('price_target', 'N/A')} target"
            for r in analyst_reports
        ])

        market_context = f"""
        Current Price: ${market_data.get('current_price', 0):.2f}
        30-day Change: {market_data.get('price_change_30d', 0):.1f}%
        P/E Ratio: {market_data.get('pe_ratio', 0):.1f}
        Market Cap: ${market_data.get('market_cap', 0)/1e9:.1f}B
        Sector: {market_data.get('sector', 'Unknown')}
        """

        prompt = f"""
        You are a professional financial analyst. Analyze {ticker}'s recent earnings and provide comprehensive investment insights.

        RECENT EARNINGS DATA:
        {filings_context}

        MANAGEMENT COMMENTARY:
        {transcript_context}

        ANALYST COVERAGE:
        {analyst_context}

        MARKET DATA:
        {market_context}

        Provide a thorough analysis in JSON format with specific, actionable insights:

        {{
          "overall_grade": "Letter grade A-F based on overall performance",
          "investment_thesis": "2-3 sentence core investment argument",
          "financial_health": {{
            "revenue_trend": "Growth/Decline analysis",
            "profitability": "Margin and earnings assessment",
            "balance_sheet": "Financial strength evaluation"
          }},
          "key_strengths": ["Specific strength 1", "Specific strength 2", "Specific strength 3"],
          "key_risks": ["Specific risk 1", "Specific risk 2", "Specific risk 3"],
          "analyst_consensus": {{
            "avg_rating": "Buy/Hold/Sell consensus",
            "price_target_range": "$XXX - $XXX",
            "sentiment_shift": "Recent changes in analyst sentiment"
          }},
          "earnings_surprises": {{
            "revenue_beat_miss": "Beat/Miss by X%",
            "eps_beat_miss": "Beat/Miss by $X.XX",
            "guidance_reaction": "Raised/Lowered/Maintained guidance"
          }},
          "competitive_position": "Market position and competitive advantages assessment",
          "valuation_assessment": "Overvalued/Fairly Valued/Undervalued with reasoning",
          "price_catalysts": ["Upcoming catalyst 1", "Upcoming catalyst 2"],
          "recommendation": "Clear Buy/Hold/Sell recommendation with timeframe",
          "risk_level": "Low/Medium/High risk assessment"
        }}
        """

        response = client.models.generate_content(
            model="gemini-1.5-flash",
            contents=prompt,
            config={"response_mime_type": "application/json"}
        )

        return json.loads(response.text)

    except Exception as e:
        st.error(f"⚠️ AI analysis failed: {e}")
        return {}

# -----------------------------
# 6️⃣ Streamlit Dashboard
# -----------------------------
st.set_page_config(
    page_title="Earnings Intelligence",
    page_icon="📊",
    layout="wide"
)

st.title("📊 AI-Powered Earnings Intelligence Platform")
st.markdown("**Comprehensive analysis combining SEC filings, earnings calls, analyst reports, and market data**")

# Input section
col1, col2, col3 = st.columns([0.5, 0.3, 0.2])
with col1:
    ticker = st.text_input("Enter stock ticker", value="AAPL", placeholder="e.g., AAPL, MSFT, GOOGL")
with col2:
    quarters = st.selectbox("Quarters to analyze", [1, 2, 3, 4], index=1)
with col3:
    analyze_button = st.button("🔍 Analyze Earnings", type="primary", use_container_width=True)

if analyze_button and ticker:
    ticker = ticker.upper()

    # Create tabs for different data sources
    tab1, tab2, tab3, tab4 = st.tabs(["📋 SEC Filings", "🎙️ Earnings Calls", "📰 Analyst Reports", "📈 Market Data"])

    # Fetch all data
    with st.spinner("🔄 Collecting earnings intelligence..."):
        sec_data = fetch_sec_earnings(ticker, quarters)
        transcripts = fetch_earnings_transcripts(ticker, quarters)
        analyst_data = fetch_analyst_sentiment(ticker)
        market_data = fetch_market_data(ticker)

    # Display raw data in tabs
    with tab1:
        st.subheader("SEC Filing Summary")
        if sec_data:
            df = pd.DataFrame(sec_data)
            st.dataframe(df, use_container_width=True)
        else:
            st.warning("No SEC filings found")

    with tab2:
        st.subheader("Earnings Call Highlights")
        for transcript in transcripts:
            with st.expander(f"{transcript.get('quarter', 'Unknown')} - {transcript.get('date', '')}"):
                st.write("**CEO Key Comments:**")
                for comment in transcript.get('ceo_comments', []):
                    st.write(f"• {comment}")

                st.write("**Key Metrics Discussed:**")
                for metric in transcript.get('key_metrics_discussed', []):
                    st.write(f"• {metric}")

    with tab3:
        st.subheader("Analyst Coverage")
        for report in analyst_data:
            with st.expander(f"{report.get('firm', 'Unknown')} - {report.get('rating', '')} ${report.get('price_target', '')}"):
                st.write(f"**{report.get('headline', '')}**")
                for point in report.get('key_points', []):
                    st.write(f"• {point}")

    with tab4:
        st.subheader("Market Performance")
        if market_data:
            col1, col2, col3, col4 = st.columns(4)
            with col1:
                st.metric("Current Price", f"${market_data.get('current_price', 0):.2f}")
            with col2:
                change_30d = market_data.get('price_change_30d', 0)
                st.metric("30-Day Change", f"{change_30d:.1f}%", f"{change_30d:.1f}%")
            with col3:
                st.metric("P/E Ratio", f"{market_data.get('pe_ratio', 0):.1f}")
            with col4:
                market_cap = market_data.get('market_cap', 0) / 1e9
                st.metric("Market Cap", f"${market_cap:.1f}B")

    # AI Analysis Section
    st.markdown("---")
    st.subheader("🤖 AI Investment Analysis")

    with st.spinner("🧠 Generating comprehensive analysis..."):
        analysis = analyze_earnings_with_ai(ticker, sec_data, transcripts, analyst_data, market_data)

    if analysis:
        # Top-level metrics
        col1, col2, col3, col4 = st.columns(4)
        with col1:
            grade = analysis.get('overall_grade', 'N/A')
            st.markdown(f"""
            <div style="background-color: #e8f5e8; padding: 1rem; border-radius: 0.5rem; text-align: center;">
                <h3 style="margin: 0; color: #2e7d2e;">📊 Overall Grade</h3>
                <h1 style="margin: 0.5rem 0 0 0; color: #2e7d2e; font-size: 3rem;">{grade}</h1>
            </div>
            """, unsafe_allow_html=True)

        with col2:
            recommendation = analysis.get('recommendation', 'N/A')
            color = "#28a745" if "Buy" in recommendation else "#ffc107" if "Hold" in recommendation else "#dc3545"
            st.markdown(f"""
            <div style="background-color: #f8f9fa; padding: 1rem; border-radius: 0.5rem; border-left: 4px solid {color};">
                <h4 style="margin: 0; color: {color};">💡 Recommendation</h4>
                <p style="margin: 0.5rem 0 0 0; font-weight: 600;">{recommendation}</p>
            </div>
            """, unsafe_allow_html=True)

        with col3:
            risk_level = analysis.get('risk_level', 'N/A')
            risk_colors = {"Low": "#28a745", "Medium": "#ffc107", "High": "#dc3545"}
            risk_color = risk_colors.get(risk_level, "#6c757d")
            st.markdown(f"""
            <div style="background-color: #f8f9fa; padding: 1rem; border-radius: 0.5rem; border-left: 4px solid {risk_color};">
                <h4 style="margin: 0; color: {risk_color};">⚠️ Risk Level</h4>
                <p style="margin: 0.5rem 0 0 0; font-weight: 600;">{risk_level}</p>
            </div>
            """, unsafe_allow_html=True)

        with col4:
            valuation = analysis.get('valuation_assessment', 'N/A')
            st.markdown(f"""
            <div style="background-color: #f8f9fa; padding: 1rem; border-radius: 0.5rem; border-left: 4px solid #17a2b8;">
                <h4 style="margin: 0; color: #17a2b8;">💰 Valuation</h4>
                <p style="margin: 0.5rem 0 0 0; font-weight: 600;">{valuation}</p>
            </div>
            """, unsafe_allow_html=True)

        # Investment thesis
        st.markdown("### 🎯 Investment Thesis")
        st.info(analysis.get('investment_thesis', 'No thesis available'))

        # Detailed analysis
        col1, col2 = st.columns(2)

        with col1:
            st.markdown("### ✅ Key Strengths")
            for strength in analysis.get('key_strengths', []):
                st.success(f"✓ {strength}")

            st.markdown("### 📈 Earnings Performance")
            earnings = analysis.get('earnings_surprises', {})
            st.write(f"**Revenue:** {earnings.get('revenue_beat_miss', 'N/A')}")
            st.write(f"**EPS:** {earnings.get('eps_beat_miss', 'N/A')}")
            st.write(f"**Guidance:** {earnings.get('guidance_reaction', 'N/A')}")

        with col2:
            st.markdown("### ⚠️ Key Risks")
            for risk in analysis.get('key_risks', []):
                st.error(f"✗ {risk}")

            st.markdown("### 🔮 Price Catalysts")
            for catalyst in analysis.get('price_catalysts', []):
                st.info(f"• {catalyst}")

        # Financial health breakdown
        st.markdown("### 💼 Financial Health Analysis")
        financial_health = analysis.get('financial_health', {})

        col1, col2, col3 = st.columns(3)
        with col1:
            st.write("**Revenue Trend**")
            st.write(financial_health.get('revenue_trend', 'N/A'))
        with col2:
            st.write("**Profitability**")
            st.write(financial_health.get('profitability', 'N/A'))
        with col3:
            st.write("**Balance Sheet**")
            st.write(financial_health.get('balance_sheet', 'N/A'))

        # Analyst consensus
        st.markdown("### 👥 Analyst Consensus")
        consensus = analysis.get('analyst_consensus', {})
        col1, col2, col3 = st.columns(3)
        with col1:
            st.metric("Average Rating", consensus.get('avg_rating', 'N/A'))
        with col2:
            st.metric("Price Target Range", consensus.get('price_target_range', 'N/A'))
        with col3:
            st.write("**Sentiment Shift**")
            st.write(consensus.get('sentiment_shift', 'N/A'))

    st.markdown("---")
    st.markdown("**Data Sources:** SEC EDGAR, Earnings Call Transcripts, Analyst Reports, Yahoo Finance | **AI Analysis:** Google Gemini")